# Generated by Django 4.0.3 on 2022-10-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='number_of_questions',
            field=models.IntegerField(default=0),
        ),
    ]
