# Generated by Django 4.0.3 on 2022-10-28 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_enrolldata_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolldata',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.courseschedule'),
        ),
    ]
