# Generated by Django 4.0.3 on 2022-06-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuthentication', '0002_remove_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminmore',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studentmore',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teachermore',
            name='user',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.RemoveField(
            model_name='user',
            name='type',
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='AdminMore',
        ),
        migrations.DeleteModel(
            name='StudentMore',
        ),
        migrations.DeleteModel(
            name='TeacherMore',
        ),
    ]
