# Generated by Django 4.0.3 on 2022-06-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuthentication', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approval',
            field=models.BooleanField(default=False),
        ),
    ]
