# Generated by Django 4.0.3 on 2022-03-28 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchOption', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enquiry',
        ),
    ]
