# Generated by Django 4.0.3 on 2022-06-17 04:21

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_slug',
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=0, editable=False, populate_from='blog_title', unique=True, verbose_name='Post Address'),
        ),
    ]
