# Generated by Django 4.0.3 on 2022-06-17 04:32

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_blog_slug_blog_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='blog_title',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='blog_title', unique=True, verbose_name='Post Address'),
        ),
    ]
