# Generated by Django 4.0.3 on 2022-09-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogpostmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostmodel',
            name='notice_file',
            field=models.FileField(blank=True, default=None, max_length=250, null=True, upload_to='notice/'),
        ),
    ]
