# Generated by Django 4.0.3 on 2022-09-27 06:12

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogpostmodel_notice_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostmodel',
            name='file_slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='notice_file', unique=True, verbose_name='file_name'),
        ),
    ]
