# Generated by Django 4.0.3 on 2022-09-27 06:13

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogpostmodel_file_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostmodel',
            name='file_slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='notice_file', unique=True, verbose_name='file_name'),
        ),
    ]
