# Generated by Django 4.0.3 on 2022-09-27 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blogpostmodel_file_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpostmodel',
            name='file_slug',
        ),
    ]
