"""
Django settings for OnlineTrainingPortal project.

Generated by 'django-admin startproject' using Django 4.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from doctest import FAIL_FAST
from pathlib import Path
import os
from re import A

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
APP_DIR = BASE_DIR / "OnlineTrainingPortal"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-yb9p)3!-76g)0wdb*+dx9t)@w1d!79mke^+_ntr##y8b^tk4=d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    
]
LOCAL_APPS = [
    'OnlineTrainingPortal.course.apps.CourseConfig',
    'OnlineTrainingPortal.blog.apps.BlogConfig',
    'OnlineTrainingPortal.searchOption.apps.SearchoptionConfig',
    'OnlineTrainingPortal.userAuthentication.apps.UserauthenticationConfig', 
    'OnlineTrainingPortal.message.apps.MessageConfig',
    'OnlineTrainingPortal.videoCall.apps.VideocallConfig',
    'OnlineTrainingPortal.administration.apps.AdministrationConfig',
    'OnlineTrainingPortal.enquiry.apps.EnquiryConfig',
    'OnlineTrainingPortal.student.apps.StudentConfig',
    'OnlineTrainingPortal.teacher.apps.TeacherConfig',
    'OnlineTrainingPortal.quizes.apps.QuizesConfig',
]
CRISPY_TEMPLATE_PACK = 'bootstrap4'
THIRD_PARTY_APPS = [
    'tinymce',
    'channels',
    'crispy_forms',
    'crispy_bootstrap4',
]

INSTALLED_APPS = DJANGO_APPS + LOCAL_APPS + THIRD_PARTY_APPS    

MIDDLEWARE = [
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'OnlineTrainingPortal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [str( APP_DIR / "templates" )],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI_APPLICATION = 'OnlineTrainingPortal.wsgi.application'
ASGI_APPLICATION = 'OnlineTrainingPortal.asgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR/'OnlineTrainingPortal'/'quizes'/'static'
]
# MEDIA_ROOT = str( APP_DIR / 'media' )
MEDIA_URL = '/media/'
AUTH_USER_MODEL = "userAuthentication.User"

if DEBUG:
  STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static/')]
else:
  STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Email Handling
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'work.anjon@gmail.com'
EMAIL_HOST_PASSWORD = 'debanjan.paul'
EMAIL_USE_TLS = True 

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Channel Layers
#In-Memory Channel Layer
# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels.layers.InMemoryChannelLayer"
#     }
# }

# Redis Channel Layer

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

LOGIN_REDIRECT_URL = 'home'
# LOGOUT_REDIRECT_URL = 'home'